import * as ActionTypes from "./ActionTypes";
import { COMMENTS } from "../shared/comments";

export const Comments = (state = COMMENTS, action) => {
  switch (action.type) {
    case ActionTypes.ADD_COMMENT:
      let comment = action.payload;
      comment.id = state.length; // will be generated by server
      comment.date = new Date().toISOString();
      console.log("add comment: " + comment);
      return state.concat(comment);
    default:
      return state;
  }
};
